[dataset]
name = "cyberbench/utkarsh-task"
description = "CyberBench Benchmark Tasks for Utkarsh-task"
authors = [{ name = "CyberBench" }]
keywords = ["security", "benchmark"]

tasks = [
    "analyze-auth-log",
    "audit-sshd-config"
]
